spring:
  application:
    name: inventory-management
  datasource:
    url: jdbc:h2:mem:rater;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: mcadmin
    password: mcadmin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    database: H2

  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true


eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    enabled: false
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


logging:
  level:
    com.ol.im: DEBUG
server:
  port: 8088
